doctrine_cache:
  custom_providers:
    dbal:
      prototype: "dwo_flagging.cache.dbal_provider"
      definition_class: "Dwo\FlaggingBundle\DependencyInjection\Definition\DbalDefinition"

  providers:
    flagging:
      php_file:
        extension: .cache.php
        directory: %kernel.cache_dir%/dwo_flagging/feature

    flagging_dbal:
      dbal:
        connection: "doctrine.dbal.default_connection"
        table: "features"

  aliases:
    dwo_flagging.cache.flagging.cache: flagging
    dwo_flagging.cache.flagging.db: flagging_dbal

services:
  dwo_flagging.cache.dbal_provider:
    class: Dwo\FlaggingBundle\Cache\DbalCache
    arguments: ["@doctrine.dbal.default_connection", "features"]
    public: false

  dwo_flagging.manager.feature.cache_and_db:
    class: Dwo\FlaggingBundle\Cache\FeatureManager
    arguments: ["@dwo_flagging.cache.flagging.cache", "@dwo_flagging.manager.feature.db_and_config"]

  dwo_flagging.manager.feature.db_and_config:
    class: Dwo\FlaggingBundle\Cache\FeatureManager
    arguments: ["@dwo_flagging.cache.flagging.db", "@dwo_flagging.manager.feature.config"]