parameters:
  dwo_flagging.manager.feature.config.class: Dwo\FlaggingBundle\Config\FeatureManager

services:
  dwo_flagging.manager.feature.config:
    class: %dwo_flagging.manager.feature.config.class%
    arguments: ["%dwo_flagging.features%"]

  dwo_flagging.manager.voter.config:
    class: Dwo\FlaggingBundle\Config\VoterManager
    arguments: [[]]
    tags:
      - { name: 'tagged_services', find_tag: "dwo_flagging.voters", lazy: true }
