services:

  dwo_flagging.manager.feature.config:
    class: Dwo\FlaggingBundle\Config\FeatureManager
    arguments: ["%dwo_flagging.features%"]

  dwo_flagging.manager.voter.config:
    class: Dwo\FlaggingBundle\Config\VoterManager
    arguments: [[]]
    tags:
      - { name: 'tagged_services', find_tag: "dwo_flagging.voters", lazy: true }

  dwo_flagging.manager.feature.config_prototype:
    class: Dwo\FlaggingBundle\Cache\ConfigPrototypeManager
    arguments: ["@dwo_flagging.cache.flagging.db"]